apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp2
  template:
    metadata:
      labels:
        app: testapp2
    spec:
      containers:
      - name: quayimage
        image: {{ .Values.images.testapp2.image }}
        imagePullPolicy: Always
