apiVersion: v1
kind: Service
metadata:
  name: testapp2-service
spec:
  selector:
    app: testapp2
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 31111
  type: NodePort
