apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp1 
  template:
    metadata:
      labels:
        app: testapp1 
    spec:
      containers:
      - name: quayimage
        image: {{ .Values.images.testapp1.image }}
        imagePullPolicy: Always
