apiVersion: v1
kind: Service
metadata:
  name: testapp1-service
spec:
  selector:
    app: testapp1
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31110
  type: NodePort
