apiVersion: v1 
kind: Service
metadata:
  name: shiny-sim-service
spec:
  selector: 
    app: shiny-sim
  type: LoadBalancer
  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31110
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31111