apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-updater-webhook-test-dcoker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-updater-webhook-test-docker
  template:
    metadata:
      labels:
        app: image-updater-webhook-test-docker
    spec:
      containers:
      - name: dockerimage
        image: docker.io/cjcocokrisp/webhooktest:1.0.0
        imagePullPolicy: Always
