apiVersion: v1
kind: Service
metadata:
  name: image-updater-webhook-test-service
spec:
  selector:
    app: image-updater-webhook-test
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31110
