apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy123
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
      - name: quayimage
        image: nginx
        imagePullPolicy: Always
