apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: testimage1=quay.io/rh-ee-ccoco/aiubug1,testimage2=quay.io/rh-ee-ccoco/webhooktest
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
      repoURL: https://github.com/cjcocokrisp/kube-labbing.git
      targetRevision: main
      path: aiu-comma-bug/chart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
