apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-image-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: nginx-image-test
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: nginx=nginx:latest
    argocd-image-updater.argoproj.io/update-strategy: semve
spec:
  project: default
  desintation:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/cjcocokrisp/kube-labbing.git
    targetRevision: HEAD
    path: nginx-image-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true