apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-image-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: nginx-image-test
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/image-list: nginx=nginx:latest
    argocd-image-updater.argoproj.io/update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:/nginx-image-test/values.yaml
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-image-test
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: "18.2.3"
      chart: nginx
      helm:
        valueFiles:
          - $values/nginx-image-test/values.yaml
    - repoURL: https://github.com/cjcocokrisp/kube-labbing.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true