apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shiny-sim
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: shiny-sim
spec:
  project: default
  desination:
    server: https://kubernetes.default.svc
    namespace: shiny-sim
  source:
    repoURL: https://github.com/cjcocokrisp/kube-labbing.git
    targetRevision: HEAD
    path: shiny-sim