apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shiny-sim
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: shiny-sim-3
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: shiny-sim
  source:
    repoURL: https://github.com/cjcocokrisp/kube-labbing.git
    targetRevision: HEAD
    path: shiny-sim
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true