apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=quay.io/rh-ee-ccoco/webhooktest:latest
    argocd-image-updater.argoproj.io/myapp.update-strategy: digest
    argocd-image-updater.argoproj.io/myapp.helm.image-spec: images.testapp2.image
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
      repoURL: https://github.com/cjcocokrisp/kube-labbing.git
      targetRevision: main
      path: aiu-digest-bug/test-chart/testapp2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
